name: Validate infra changes

on:
  issue_comment:

  pull_request_review:

  workflow_run:
    workflows: [terraform-plan]
    types: [completed]

jobs:
  check:
    name: Infra check

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      statuses: write

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Set check status
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          status: ${{ job.status }}
          context: Infra check
          sha: ${{ github.event.workflow_run.head_sha }}
      - name: Set check status
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          status: ${{ job.status }}
          context: "Another commit status!"
          sha: ${{ github.event.workflow_run.head_sha }}
