name: Test PR Review

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number

permissions: write-all

jobs:
  review:
    name: Test Review

    runs-on: ubuntu-latest

    steps:
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.PR_TOKEN }}
          number: ${{ inputs.pr }}
