name: Test PR Review

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number

jobs:
  review:
    name: Test Review

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/github-script@v7
        name: PR Review
        with:
          github-token: $${ secrets.PR_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr }},
              event: "APPROVE"
            });
