name: Test PR Comment

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number

permissions:
  contents: read
  issues: write

jobs:
  comment:
    name: Test Review

    runs-on: ubuntu-latest

    steps:
      # - name: Generate GitHub App token
      #   id: generate_token
      #   uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_KEY }}
      - name: Add PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.pr }},
              body: "A test comment!!"
            });
