name: Test PR Review

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number

jobs:
  review:
    name: Test Review

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      statuses: write

    steps:
      - uses: actions/github-script@0.8.0
        name: PR Review
        with:
          script: |
            await github.rest.pulls.createReview({
            owner: ${{ github.repository_owner }},
            repo: "check-test",
            pull_number: ${{ inputs.pr }},
            body: "",
            event: "APPROVE"
            })
